name: Example

on:
  push:
    branches:
      - main

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print the Dockerfile
        run: cat Dockerfile